name: Build and Publish Proxy Image
on:
  push:
    branches:
      - main
      - master
      - 'release-*'
    tags:
        - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.THANKSDOC_USER }}
          password: ${{ secrets.THANKSDOC_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          no-cache: true
          push: true
          tags: thanksdoc/proxy:${{env.ARTIFACT_VERSION}},thanksdoc/proxy:latest
 
